// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24.01.2025, 10:51:28
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/kassa/kassa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/kassa/kassa/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/kassa/kassa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/kassa/kassa/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/kassa/kassa/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/kassa/kassa/plugins/**/*.{js,ts,mjs}","D:/kassa/kassa/composables/**/*.{js,ts,mjs}","D:/kassa/kassa/utils/**/*.{js,ts,mjs}","D:/kassa/kassa/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/kassa/kassa/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/kassa/kassa/app.config.{js,ts,mjs}","D:/kassa/kassa/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;